### ISSUE TITLE
`typedDefer`?

### ISSUE THREAD

**Issue by frontsideair** [kiliman/remix-typedjson#20] opened 2023-01-30 21:33 UTC
Now that Remix is React-Router'ed, I think a wrapper around `defer` is needed. A `useTypedAsyncValue` counterpart may be needed as well.

**Comment by kiliman** [comment] 2023-01-30 21:53
Yes, I haven't had a chance to add support for `defer`, but it is on my TODO list.

**Comment by TheRealFlyingCoder** [comment] 2023-02-10 04:23
I'm just here to say that i'm waiting eagerly for the typedDefer update haha

**Comment by dteknolove** [comment] 2023-02-10 21:19
Thanks for create this awesome library. I hope this wil be well maintained.

**Comment by kiliman** [comment] 2023-02-11 01:00
Working on this now. Almost there.

**Comment by dev-xo** [comment] 2023-02-17 16:59
Looking for it too @kiliman! 🎉

**Comment by sixers** [comment] 2023-03-10 21:40
Hey, any update on this?

**Comment by dev-xo** [comment] 2023-03-19 23:17
+1 Any update on this? 
Would be amazing to see a wrapper arround `defer` @kiliman

**Comment by kiliman** [comment] 2023-03-21 21:01
The more I work on this, the more I realize it may not be possible without help from Remix.

I can get the "fast data" transferred just fine since I know the values and the "types" at call time. However, I don't have the actual data for "deferred data," just a Promise, so I cannot serialize and send the metadata.

The issue is that Remix doesn't provide any hooks into the deferred response pipeline, so I can't use the typedjson serializer on the Promise result.

I could create a patch, but that's not a long-term solution. Ideally, Remix would provide hooks for an encode/decode function (default being `JSON.stringify/parse`).

I'll keep you all posted.

```ts
function enqueueTrackedPromise(
  controller: any,
  encoder: TextEncoder,
  settledKey: string,
  promise: TrackedPromise
) {
  if ("_error" in promise) {
    controller.enqueue(
      encoder.encode(
        "error:" +
          JSON.stringify({
            [settledKey]: serializeError(promise._error),
          }) +
          "\n\n"
      )
    );
  } else {
    controller.enqueue(
      encoder.encode(
        "data:" +
          JSON.stringify({ [settledKey]: promise._data ?? null }) +
          "\n\n"
      )
    );
  }
}
```
https://github.com/remix-run/remix/blob/72c22b3deb9e84e97359b481f7f2af6cdc355877/packages/remix-server-runtime/responses.ts#L198-L223

**Comment by TheRealFlyingCoder** [comment] 2023-03-21 21:11
That's rough... It might pay to push for an update to the system anyway, they've mentioned it's not where they want it right now?

It wouldn't be a breaking change for them to add the hook, so I don't think they'd reject if you had the explanation and a PR?

**Comment by kiliman** [comment] 2023-03-21 21:29
Yeah, I'm going to play with adding that feature. At least show there's a need and that it wouldn't be intrusive.

**Comment by kiliman** [comment] 2023-03-21 21:39
I added this to _entry.server_ just to see what would happen and sure enough all calls to `JSON.stringify/parse` got rerouted.

```ts
// monkey patch JSON.stringify and JSON.parse
let oldStringify = JSON.stringify;
let oldParse = JSON.parse;

JSON.stringify = function (
  value: any,
  replacer?: (
    this: any,
    key: string,
    value: any
  ) => any | (number | string)[] | null,
  space?: string | number
) {
  console.log("stringify", value);
  return oldStringify(value, replacer, space);
};
JSON.parse = function (
  text: string,
  reviver?: (this: any, key: string, value: any) => any
) {
  console.log("parse", text);
  return oldParse(text, reviver);
};
```
Anyway, I may be able to handle this entirely in userland.

**Comment by TheRealFlyingCoder** [comment] 2023-03-22 01:02
That is filthy but I love it haha

**Comment by kiliman** [comment] 2023-03-29 21:00
Making progress. Deferred data is now encoded via `typedjson`. Unfortunately, it does require a patch. Hopefully, we'll get something like this added to the core.

In *entry.server*, you add the following line. This replaces the standard JSON calls.

```ts
setDataTransformer({
  encode: typedjson.stringifyRemix,
  decode: typedjson.deserializeRemix,
});
```

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/47168/228665810-c458fe62-ec8a-4382-a793-2ff57493f703.png">

**Comment by TheRealFlyingCoder** [comment] 2023-03-29 21:02
I'll give it a go today in my project and let you know if I find any issues 👍

**Comment by kiliman** [comment] 2023-03-29 22:42
Sorry if I wasn't clear, but this is still work on progress. I hope to have a release by the end of the week. Thanks!

**Comment by TheRealFlyingCoder** [comment] 2023-03-29 22:43
> Sorry if I wasn't clear, but this is still work in progress. I hope to have a release by the end of the week. Thanks!

I was thinking that when I sent the message and saw there was no release after haha All good!

**Comment by KingSora** [comment] 2023-04-03 07:34
@kiliman Couldn't you do something like this:

```js
// serialize responses from promises on the server as soon as they resolve
const typedDefer = (data) => {
  Object.entries(data).forEach(([key, value]) => {
    if (isPromise(value) {
      value.then((data) => serialize(data));
    }
    else {
      serialize(value)
    }
  });
};

// deserialize responses from promises on the client as soon as they resolve
const TypedAwait = (props) => {
  return <Await {...props}>
    {(resolvedData) => props.children(deserialize(resolvedData))}
  </Await>
}

const loader = () => {
  //...
  const myPromise = fetch(/* ... */);
  return typedDefer({ myPromise });
}

export default function Component() {
  const { myPromise } = useTypedDefer<typeof loader>();
  
  return <Suspense fallback={<p>Loading..</p>}>
      <TypedAwait
        resolve={myPromise }
        errorElement={<p>Error!</p>}>
          {(response) => {
            return <p>hi</p>;
          }}
      </TypedAwait>
    </Suspense>
}
```

This works at least on my end.. `useTypedDefer` is basically a wrapper around `useLoaderData` or which knows whether a field is a promise or not.

**Comment by dev-xo** [comment] 2023-04-17 22:50
Interesting... also nice progress @kiliman! 
I would love to see a stable release, or some progress on this.

What about @KingSora comment @kiliman?
Could be some sort of solution / alternative?

I'm happy to see some of you are already working on this.
Keep it up guys! And thank you for the efforts!

**Comment by dev-xo** [comment] 2023-05-06 03:45
Any updates on this? Would be amazing to have some news @kiliman!
Thanks for the work you have set into this!

**Closed** 2023-10-12 23:36 UTC

**Comment by dev-xo** [comment] 2023-10-12 23:40
Thank you so much @kiliman! Been waiting for this one! 🎉🙏

**Comment by kiliman** [comment] 2023-10-13 12:19
BTW: I just want to thank @KingSora for posting his snippet. It was the basis for the actual working version. 🙌

**Comment by kiliman** [comment] 2023-10-13 15:45
If you're using `typeddefer` in your project, let me know how it's working out for you. I hope I covered all the edge-cases.
